eureka:
  instance:
    prefer-ip-address: true
example:
  property: '"ZUUL : Default Server Status"'
hystrix:
  command:
    default:
      excution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
logging:
  level:
    com:
      netflix: INFO
      tyn:
        bnk: INFO
    org:
      springframework:
        web: INFO
zuul:
  debug:
    request: true
  prefix: /bnk
  routes:
    bnkauthserver: /a/**
    concept: /c/**
    harang: /h/**
    msgconcept: /mc/**
    msgharang: /mh/**
  sensitiveHeaders: Cookie,Set-Cookies
