server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/harang,classpath:config/concept,classpath:config/bnksvcgateway,classpath:config/bnkauthserver,classpath:config/msgconcept,classpath:config/msgharang
  profiles:
    active: native
