eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    stream:
      bindings:
        conceptchannel:
          content-type: application/json
          destination: orgChgConcept
          group: harangGroup
      kafka:
        binder:
          brokers: localhost
          zknodes: localhost
  redis:
    host: redis
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
  zipkin:
    baseUrl: localhost:9411
